In [60]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib tk

In [48]:
# read in data
data_folder = "D:/OneDrive/Code/WaveGVS/Data/002/"
data_file = data_folder + "002_waveGVS__20180803_151058.txt"
df = pd.read_csv(data_file, sep="; ", engine="python")

In [19]:
df.head(10)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>trial_nr</th>
      <th>current</th>
      <th>frequency</th>
      <th>line_offset</th>
      <th>line_ori</th>
      <th>amplitude</th>
      <th>phase</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>1.5</td>
      <td>0.5</td>
      <td>0.0</td>
      <td>[0.0, -0.052335956242943828, -0.10452846326765...</td>
      <td>[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>45.0</td>
      <td>[45.0, 44.947735768366172, 44.896044154591124,...</td>
      <td>[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>1.5</td>
      <td>0.5</td>
      <td>90.0</td>
      <td>[90.0, 89.895328087514116, 89.790943073464689,...</td>
      <td>[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>2.0</td>
      <td>1.0</td>
      <td>-45.0</td>
      <td>[-45.0, -45.104528463267656, -45.2079116908177...</td>
      <td>[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>2.0</td>
      <td>0.5</td>
      <td>-45.0</td>
      <td>[-45.0, -45.052335956242942, -45.1045284632676...</td>
      <td>[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
    <tr>
      <th>5</th>
      <td>6</td>
      <td>1.5</td>
      <td>1.0</td>
      <td>0.0</td>
      <td>[0.0, -0.052264231633826728, -0.10395584540887...</td>
      <td>[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>1.5</td>
      <td>0.5</td>
      <td>45.0</td>
      <td>[45.0, 44.973832021878529, 44.947735768366172,...</td>
      <td>[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>90.0</td>
      <td>[90.0, 89.895471536732344, 89.792088309182247,...</td>
      <td>[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
    <tr>
      <th>8</th>
      <td>9</td>
      <td>1.0</td>
      <td>0.5</td>
      <td>-45.0</td>
      <td>[-45.0, -45.052335956242942, -45.1045284632676...</td>
      <td>[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10</td>
      <td>2.0</td>
      <td>0.5</td>
      <td>45.0</td>
      <td>[45.0, 44.947664043757058, 44.895471536732344,...</td>
      <td>[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, ...</td>
      <td>[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...</td>
    </tr>
  </tbody>
</table>
</div>

In [20]:
df.dtypes

trial_nr         int64
current        float64
frequency      float64
line_offset    float64
line_ori        object
amplitude       object
phase           object
dtype: object

In [49]:
# outer list comprehension turns string into list
# nested: turn strings inside the list into float
df["line_ori"] = [[float(y) for y in x.strip("[]").split(",")] for x in df["line_ori"]]
df["amplitude"] = [[float(y) for y in x.strip("[]").split(",")] for x in df["amplitude"]]
df["phase"] = [[float(y) for y in x.strip("[]").split(",")] for x in df["phase"]]

In [63]:
# get conditions
currents = sorted(df["current"].unique())
frequencies = sorted(df["frequency"].unique())
c = len(currents)
f = len(frequencies)

In [64]:
# plot raw data traces
count = 0
for curr in currents:
    for freq in frequencies:
        count += 1
        plt.subplot(c, f, count)
        selection = df[(df["current"] == curr) & (df["frequency"] == freq)]
        for index, row in selection.iterrows():
            orientation = row["line_ori"]
            # collapse over offset angles
            orientation = [x - row["line_offset"] for x in orientation]
            samples = np.arange(0, len(orientation))

            plt.plot(samples, orientation)

        plt.title("{0} mA, {1} Hz".format(curr, freq))
        plt.ylabel("line angle (deg)")
        plt.xlabel("t (samples)")
plt.tight_layout()